### ISSUE TITLE
Rename project creates backup files with '-e' extension

### ISSUE THREAD

**Issue by rossta** [infinitered/phoenix_base#25]
On my Mac (MacBook Pro, 2011, OSX 10.10.5), when I run rename project as described in the `README`: `bin/rename_project PhoenixBase phoenix_base CoolProject cool_project`, the script creates three additional files for each changed file. For example:

``` sh
$ bin/rename_project PhoenixBase phoenix_base CoolProject cool_project
$ ls | grep mix.exs
mix.exs
mix.exs-e
mix.exs-e-e
mix.exs-e-e-e
```

I believe each usage of `sed -i -e ...` is interpreting `-e` as the file extension argument to `-i` instead of as an empty file extension as is intended; three calls to `sed -i -e...`, three backup files created. Using `sed -i '' -e ...` fixe the problem on my Mac, though I'm unsure about the interoperability with Linux.

**Comment by jamonholmgren** [comment]
@rossta Thanks for reporting, sorry about the delay. @danielberkompas, any thoughts on this? cc @zberkom

**Comment by danielberkompas** [comment]
@rossta What version of `sed` do you have? The `rename_project` script was written on OS X 10.11, so my guess is that it has to do with an older version of `sed`.

**Comment by rossta** [comment]
@danielberkompas So, I originally ran into this issue on OS X 10.10. I also reproduced on OS X 10.12, but with a MacBook from mid 2014, which started on OS X 10.9; it would seem the `sed` utility is not upgraded along with the OS.

I was able to see the correct results after installing `gnu-sed` formula from Homebrew. I'd be happy to provide a note in the README if you think it would be helpful.

**Comment by jamonholmgren** [comment]
@rossta Late, late response, but yes, that would be great if you could add a note!
