### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by railsmechanic** [infinitered/phoenix_base#26]
First, many thanks for this project. It's a great starter for new Phoenix applications.
But what license have you destined for this project? Can everybody use it and/or derive own solutions from it?

**Comment by jamonholmgren** [comment]
@railsmechanic Thanks for the kind words! Let me check with the team and get back with you.

**Comment by jamonholmgren** [comment]
@railsmechanic MIT -- will update soon per #27.

**Comment by railsmechanic** [comment]
Many thanks! 👍

**Comment by railsmechanic** [comment]
Thanks for adding MIT License
