### ISSUE TITLE
Add const file for string

### ISSUE THREAD

**Issue by ajrobertsonio** [infinitered/phoenix_base#33]
How should we manage strings within our phoenix applications? Flash messages, error messages, validation messages, etc.

**Comment by jamonholmgren** [comment]
@codeithuman Maybe we should move this to [Firebird](https://github.com/infinitered/firebird) and discuss it there, since it's replacing phoenix_base.

**Comment by ajrobertsonio** [comment]
Shoot, I already did and forgot to close this issue! https://github.com/infinitered/firebird/issues/11
