### ISSUE TITLE
Switch from brunch to webpack / Setup front-end stack

### ISSUE THREAD

**Issue by yulolimum** [infinitered/phoenix_base#8]
@ryanlntn and I were working on setting up a new project and thought that webpack could be a better fit for our projects. Also, it would be a good idea to have bourbon neat and bitters included with this base so that the time for FE setup is decreased. There were a lot of organizational rules and helpful grid configs in place in the middleman base that could be included with this base.

**Comment by ajrobertsonio** [comment]
I definitely agree with @yulianglukhenko and @ryanlntn here. Brunch is the most frustrating part of Phoenix. On another project Webpack's [code splitting](http://webpack.github.io/docs/code-splitting.html) would have been very helpful. I could not get code splitting in Brunch to work and ended up having to load admin javascript for users and vise versa.

**Comment by jamonholmgren** [comment]
@yulianglukhenko Approved to submit a PR. ;)
